##### - [User Registration] success registration
POST http://localhost:3000/api/users/register
Accept: application/json
Content-Type: application/json

{
	"username": "administrator",
	"first_name": "Ram",
	"last_name": "Tech",
	"password": "bluelock",
	"position": "admin",
	"start_date": "2024-06-09",
	"status": 1
}

##### - [User Registration] failed registration
POST http://localhost:3000/api/users/register
Accept: application/json
Content-Type: application/json

{
}

#### - [Authenticating Users] failed response
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
	"username": "",
	"password": ""
}

#### - [AUthenticating Users] failed response
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
	"username": "Master",
	"password": "nbgfsdfsd"
}

#### - [Authenticating Users] success response
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
	"username": "Master",
	"password": "bluelock"
}

#### - [Refresh Token] success response
POST http://localhost:3000/api/auth/token/refresh
Accept: application/json
Content-Type: application/json

{
	"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyZWZyZXNoIjp0cnVlLCJpYXQiOjE3MTY1NzM0NDgsImV4cCI6MTcxNzE3ODI0OH0.YVJEuDsEEZqacPdI--ypfPJqOa8cNaCTcmS54n4O8OU"
}

#### - [Refresh Token] failed response
POST http://localhost:3000/api/auth/token/refresh
Accept: application/json
Content-Type: application/json

{
	"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyZWZyZXNoIjpmYWxzZSwiaWF0IjoxNzE2NTczNDgyLCJleHAiOjE3MTY1NzQzODJ9.68J7EqN6ss3Rano4MEWuIWp6ExSKZTK-Gx9FzxhwdNw"
}

#### - [Verify access token] failed/success response
POST http://localhost:3000/api/auth/token/verify
Accept: application/json
Content-Type: application/json

{
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyZWZyZXNoIjpmYWxzZSwiaWF0IjoxNzE2NzQyOTYzLCJleHAiOjE3MTY3NDI5ODN9.u4fyq3zdijY_xwxkDK00oFCac88RD2uGZVkBOua5yXU"
}

### = [GET all users] success
GET http://localhost:3000/api/users/all
Accept: application/json


### = [UPDATE a user] success
POST http://localhost:3000/api/users/update
Accept: application/json
Content-Type: application/json

{
	"username": "blue-master",
	"first_name": "Master",
	"id": 4
}

### = [UPDATE a user] failed
POST http://localhost:3000/api/users/update
Accept: application/json
Content-Type: application/json

{
}

### = [Add new Product Category] success
POST http://localhost:3000/api/product-category/register
Accept: application/json
Content-Type: application/json

{
	"name": "Laptops"
}

### = [Add new Product Category] failed
POST http://localhost:3000/api/product-category/register
Accept: application/json
Content-Type: application/json

{
}

### = [Get all Product Category] success
GET http://localhost:3000/api/product-category/all
Accept: application/json
Content-Type: application/json


### = [Get all accounts] success
GET http://localhost:3000/api/settings/accounts/all
Accept: application/json
Content-Type: application/json

### = [Get all suppliers] success
GET http://localhost:3000/api/suppliers/all
Accept: application/json
Content-Type: application/json

### = [Add new suppliers] success
POST http://localhost:3000/api/suppliers/register
Accept: application/json
Content-Type: application/json

{
	"company_name": "ABC Company",
	"first_name": "Rynn Harvey",
	"last_name": "Aparece",
	"phone": "09674837534",
	"address": {
		"address1": "Sample address",
		"address2": "Sample address",
		"city": "Blue City",
		"postal": "904596"
	}
}

### = [Update supplier] success
POST http://localhost:3000/api/suppliers/update
Accept: application/json
Content-Type: application/json

{
	"id": 1,
	"company_name": "ABC Company",
	"first_name": "Rynn",
	"last_name": "Aparece",
	"phone": "09674837534",
	"address": {
		"id": 1,
		"address1": "Sample address updated ",
		"address2": "Sample address updated",
		"city": "Blue City",
		"postal": "904596"
	}
}

### = [DELETE supplier] success
DELETE  http://localhost:3000/api/suppliers/delete
Accept: application/json
Content-Type: application/json

{
	"id": 2
}


### = [GET all products] success
GET http://localhost:3000/api/products/all
Accept: application/json
Content-Type: application/json

### = [GET all product item codes] success
GET http://localhost:3000/api/products/item-code
Accept: application/json
Content-Type: application/json

### = [Register product] success
POST http://localhost:3000/api/products/register
Accept: application/json
Content-Type: application/json

{
	"brand": "Testing",
	"category_id": 39,
	"cost": 567,
	"expense_account": 43,
	"income_account": 39,
	"item_code": "a027420f",
	"name": "Testing 3",
	"price": 567,
	"product_setting_id": 2,
	"purchase_description": "This is a test",
	"quantity_in_stock": 4,
	"sale_description": "This is a test",
	"status": "",
	"suppliers": [11, 12],
	"type": "inventory"
}

### = [Update product] success
POST http://localhost:3000/api/products/update
Accept: application/json
Content-Type: application/json

{
	"id": 1,
	"name": "PRINTERS"
}

### = [Delete product] success
DELETE http://localhost:3000/api/products/delete
Accept: application/json
Content-Type: application/json

{
	"id": 1
}

### - [All Product Setting] success
GET http://localhost:3000/api/product-setting/all
Accept: application/json
Content-Type: application/json

### - [Register Product Setting] Error
POST http://localhost:3000/api/product-setting/register
Accept: application/json
Content-Type: application/json

{
	"point": 3,
	"products": []
}

### - [Update Product Setting] success
POST http://localhost:3000/api/product-setting/update
Accept: application/json
Content-Type: application/json

{
	"point": 5,
	"id": 1,
	"products": [12,13]
}

### - [Delete Product Setting] success
DELETE http://localhost:3000/api/product-setting/delete
Accept: application/json
Content-Type: application/json

{
	"id": 4
}
