module.exports = [
  {
    name: "Hardware",
    type: "income",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Software",
    type: "income",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Services",
    type: "income",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Others",
    type: "income",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Rentals",
    type: "expense",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Travel",
    type: "expense",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Mail Allowance",
    type: "expense",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Cost of Goods",
    type: "expense",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Salaries",
    type: "expense",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Office Supplies",
    type: "expense",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Marketing",
    type: "expense",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Utilities",
    type: "expense",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Interest Income",
    type: "income",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Consulting",
    type: "income",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Taxes",
    type: "expense",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Depreciation",
    type: "expense",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Insurance",
    type: "expense",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bad Debts",
    type: "expense",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Employee Benefits",
    type: "expense",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Legal and Professional Fees",
    type: "expense",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bank Charges",
    type: "expense",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Income Tax",
    type: "expense",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
