module.exports = [
  {
    company_name: "ABC Company",
    annotation: "Mr.",
    first_name: "John",
    last_name: "Doe",
    email: "info@abc.com",
    phone: "09876737572",
    telephone: "09485895835",
    fax: "09485895835",
    address: {
      address1: "Morinstrain Str",
      address2: "Modigdgg djg",
      city: "City 1",
      province: "Cebu",
      postal: "09586",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    company_name: "DEF Company",
    annotation: "Ms.",
    first_name: "Jane",
    last_name: "Bixx",
    email: "info@def.com",
    phone: "09876737572",
    telephone: "09485895835",
    fax: "09485895835",
    address: {
      address1: "Morinstrain Str",
      address2: "Modigdgg djg",
      city: "City 1",
      province: "Bohol",
      postal: "09586",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    company_name: "GHI Company",
    annotation: "Mr.",
    first_name: "Bob",
    last_name: "Luis",
    email: "info@def.com",
    phone: "09876737572",
    telephone: "09485895835",
    fax: "09485895835",
    address: {
      address1: "Morinstrain Str",
      address2: "Modigdgg djg",
      city: "City 1",
      province: "Bohol",
      postal: "09586",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
